// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkD7HN19_Dc9lcUxCD80vX9lTj-aN_UJc',
    appId: '1:80532718271:web:69e6f08b1d37544fab7c0a',
    messagingSenderId: '80532718271',
    projectId: 'loan-management-30e1a',
    authDomain: 'loan-management-30e1a.firebaseapp.com',
    storageBucket: 'loan-management-30e1a.firebasestorage.app',
    measurementId: 'G-S5HBQCTTK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKlxyS9xPO4YHiofehI0aUXHb9LS-nzP8',
    appId: '1:80532718271:android:e7887c213df8c382ab7c0a',
    messagingSenderId: '80532718271',
    projectId: 'loan-management-30e1a',
    storageBucket: 'loan-management-30e1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8bUJhguPnCJZ4d7jwrAegUoUTUc1mGQI',
    appId: '1:80532718271:ios:b21b807bc2d6ff89ab7c0a',
    messagingSenderId: '80532718271',
    projectId: 'loan-management-30e1a',
    storageBucket: 'loan-management-30e1a.firebasestorage.app',
    iosBundleId: 'com.example.loanManagement',
  );
}
